### ISSUE TITLE
코드 중복 

### ISSUE THREAD

**Issue by rnntnp** [steve30572/SKKU_TIMETABLE#15]
https://github.com/steve30572/SKKU_TIMETABLE/blob/63675516dc2cddbd79095d1a41d271edac6cfd6e/index.html#L192
required meta tags , bootstrap css 부분이 중복됩니다. 이부분은 삭제해도 될듯

**Comment by steve30572** [comment]
## head tag 는 겹치는 부분 지웠습니다
