### ISSUE TITLE
Timetable에 과목이 옳게 표시되지 않는 버그 

### ISSUE THREAD

**Issue by rnntnp** [steve30572/SKKU_TIMETABLE#20]
과목을 많이 추가하는 경우 
![image](https://user-images.githubusercontent.com/60357053/119323232-70a89480-bcb9-11eb-8f83-5caae1891b25.png)
미적분 1, 컴퓨터네트워크개론과 같이 한 칸 옆으로 밀려 보이기도 하고 

![image](https://user-images.githubusercontent.com/60357053/119323353-92098080-bcb9-11eb-9ba6-830cbaa220a4.png)

(영어쓰기, 일반물리학1) 이 겹치는 부분처럼 밀리기도 합니다. 
이런 버그가 어째서 생기는 걸까요..? 조언해주시면 감사하겠습니다 ㅠㅠ

**Comment by steve30572** [comment]
#### 사용하신 insertBefore() 함수가 그자리에 이미 뭔가가 있으면 그 다음자리(옆자리)에 간다는거 같아요
#### 예를들어 3개의 과목이 같은 시간에 수업을 진행한다면 저런 현상이 나올거 같기도 하네요

**Comment by rnntnp** [comment]
manageoverlap()함수 수정으로 해결했습니다~!!

**Comment by steve30572** [comment]
modified manageoverlap()
