### ISSUE TITLE
시간표로 보기가 잘 안되는 경우가 존재합니다

### ISSUE THREAD

**Issue by steve30572** [steve30572/SKKU_TIMETABLE#21]
@rnntnp 
#### 오픈소스실습, 영어쓰기, 소프트웨어공학개론, 알고리즘개론, 컴퓨터네트워크개론을 책가방에 추가하고 시간표로 보기 누르면 결과가 틀리게 나오는 것 같아요

**Comment by rnntnp** [comment]
timeTable.html의 insertbefore 문제였던것같습니다 해결했습니다~
